package tmacsoftware.whitematter;

import tmacsoftware.ursql.*;
import java.util.Vector;

public class Sticklet extends javax.swing.JFrame
{

    private String process = "";
    private String note = "";
    private StickletHandler stickletHandler = null;
    private ProcessLoader processLoader = null;

    public Sticklet(String process, String note, StickletHandler stickletHandler)
    {
        initComponents();

        this.processLoader = new ProcessLoader(this);
        this.processLoader.load();

        this.setProcess(process);
        this.setNote(note);
        this.stickletHandler = stickletHandler;

        this.comboProcess.addActionListener(new java.awt.event.ActionListener()
        {

            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkEditable();
            }
        });
    }

    /**
     * Save process name and switch combo box to appropriate value
     * @param process Process name
     */
    public void setProcess(String process)
    {
        this.process = process;

        // check if process is found in database
        UrSQLEntity entity = this.processLoader.controller.getEntity("process");
        if (entity.isEmpty() && process.compareTo("") != 0)
        {
            // create a new item if not
            this.comboProcess.addItem(process);
            this.comboProcess.setSelectedItem(process);
            return;
        }

        this.comboProcess.setSelectedItem(this.processLoader.getName(process));
    }

    /**
     * Get process name from combo box
     * @return Process name
     */
    public String getProcess()
    {
        this.process = this.processLoader.getProcess(this.comboProcess.getSelectedItem().toString());        
        return this.process;
    }

    /**
     * Save note text and adjust textbox value
     * @param note Text for note
     */
    public void setNote(String note)
    {
        this.note = note;
        this.txtNote.setText(note);
    }

    /**
     * Get note text from textbox
     * @return Note text
     */
    public String getNote()
    {
        this.note = this.txtNote.getText();
        return this.note;
    }

    /**
     * Add item to process combo box
     * @param item Item to add to combo box
     */
    public void addProcessItem(String item)
    {
        this.comboProcess.addItem(item);
    }

    /**
     * Make combo box editable when "Other" is selected
     */
    public void checkEditable()
    {
        if (this.comboProcess.getSelectedItem().toString().compareTo("Other") == 0)
        {
            this.comboProcess.setEditable(true);
        }
        else
        {
            this.comboProcess.setEditable(false);
        }
    }

    /**
     * Save note, by modifying values if note for given process already exists
     * or creating a new note
     */
    public void save()
    {
        this.stickletHandler.saveSticklet(this.getProcess(), this.getNote());
    }

    /**
     * Delete note from database
     */
    public void delete()
    {
        this.stickletHandler.deleteSticklet(this.getProcess(), this.getNote());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProcess = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblNote = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        comboProcess = new javax.swing.JComboBox();

        setAlwaysOnTop(true);

        lblProcess.setText("Process:");

        btnSave.setText("Save and Close");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete and Close");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblNote.setText("Note:");

        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane1.setViewportView(txtNote);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProcess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboProcess, 0, 310, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave))
                    .addComponent(lblNote))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProcess)
                    .addComponent(comboProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
    {//GEN-HEADEREND:event_btnSaveActionPerformed
        this.save();
        this.setVisible(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteActionPerformed
    {//GEN-HEADEREND:event_btnDeleteActionPerformed
        this.delete();
        this.setVisible(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox comboProcess;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblProcess;
    private javax.swing.JTextArea txtNote;
    // End of variables declaration//GEN-END:variables
}
